name: Daily Music Chart Collection

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 16 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v4

      # 2. Git 설정
      - name: Set Git Config
        run: |
          git config --global user.email "webstoryboy@naver.com"
          git config --global user.name "websseu"

      # 3. Python 설정
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # 4. Python 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install requests beautifulsoup4 lxml pandas selenium webdriver_manager

      # 5. 스크립트 실행 및 커밋
      - name: Run Scripts and Commit Changes
        run: |
          python3 korea-genie.py
          python3 korea-bugs.py
          python3 korea-flo.py
          python3 korea-vibe.py
          python3 korea-melon.py
          git add korea/**/*.json
          git commit -m "Korea Chart Updated - $(date +"%Y-%m-%d")" || echo "No changes to commit"

          python3 world-youtube.py
          git add youtube/**/*.json
          git commit -m "Youtube Chart Updated - $(date +"%Y-%m-%d")" || echo "No changes to commit"

          python3 world-apple.py
          git add apple/**/*.json
          git commit -m "Apple Chart Updated - $(date +"%Y-%m-%d")" || echo "No changes to commit"

      # 6. 변경사항 푸시
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
