import bcrypt from 'bcryptjs'
import { InputData } from './types'
import { toSlug } from './utils'

const inputData: InputData = {
  users: [
    {
      name: 'webstoryboy',
      email: 'webstoryboy@naver.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'Admin',
      image: '/face/face01.jpg',
      visitCount: 0,
      verificationToken: null,
      isActive: true,
    },
  ],
  posts: [
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-1)',
      slug: toSlug('webdesign2025 layout A1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign01.tsx',
      images: 'webdesign01.jpg',
      youtubeId: 'PIuf4lZj93g',
      tags: ['웹디자인개발기능사', '레이아웃', 'A-1'],
      description: '웹디자인개발기능사 레이아웃 A-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-01T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-2)',
      slug: toSlug('webdesign2025 layout A2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign02.tsx',
      images: 'webdesign02.jpg',
      youtubeId: '4hq1IfonmJo',
      tags: ['웹디자인개발기능사', '레이아웃', 'A-2'],
      description: '웹디자인개발기능사 레이아웃 A-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-02T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-3)',
      slug: toSlug('webdesign2025 layout A3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign03.tsx',
      images: 'webdesign03.jpg',
      youtubeId: '66WW2KnLrYc',
      tags: ['웹디자인개발기능사', '레이아웃', 'A-3'],
      description: '웹디자인개발기능사 레이아웃 A-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-03T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-4)',
      slug: toSlug('webdesign2025 layout A4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign04.tsx',
      images: 'webdesign04.jpg',
      youtubeId: '1JG_bLrsLKo',
      tags: ['웹디자인개발기능사', '레이아웃', 'A-4'],
      description: '웹디자인개발기능사 레이아웃 A-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-04T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-1)',
      slug: toSlug('webdesign2025 layout B1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign05.tsx',
      images: 'webdesign05.jpg',
      youtubeId: 'rInbiYfMO3E',
      tags: ['웹디자인개발기능사', '레이아웃', 'B-1'],
      description: '웹디자인개발기능사 레이아웃 B-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-05T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-2)',
      slug: toSlug('webdesign2025 layout B2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign06.tsx',
      images: 'webdesign06.jpg',
      youtubeId: 'yKgtQb61ckE',
      tags: ['웹디자인개발기능사', '레이아웃', 'B-2'],
      description: '웹디자인개발기능사 레이아웃 B-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-06T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-3)',
      slug: toSlug('webdesign2025 layout B3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign07.tsx',
      images: 'webdesign07.jpg',
      youtubeId: 'gh92WmPHOHQ',
      tags: ['웹디자인개발기능사', '레이아웃', 'B-3'],
      description: '웹디자인개발기능사 레이아웃 B-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-07T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-4)',
      slug: toSlug('webdesign2025 layout B4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign08.tsx',
      images: 'webdesign08.jpg',
      youtubeId: 'JZDjlq_Cv6g',
      tags: ['웹디자인개발기능사', '레이아웃', 'B-4'],
      description: '웹디자인개발기능사 레이아웃 B-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-08T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-1)',
      slug: toSlug('webdesign2025 layout C1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign09.tsx',
      images: 'webdesign09.jpg',
      youtubeId: 'icLXOd71hZc',
      tags: ['웹디자인개발기능사', '레이아웃', 'C-1'],
      description: '웹디자인개발기능사 레이아웃 C-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-09T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-2)',
      slug: toSlug('webdesign2025 layout C2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign10.tsx',
      images: 'webdesign10.jpg',
      youtubeId: 'hen4nHzIbfY',
      tags: ['웹디자인개발기능사', '레이아웃', 'C-2'],
      description: '웹디자인개발기능사 레이아웃 C-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-10T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-3)',
      slug: toSlug('webdesign2025 layout C3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign11.tsx',
      images: 'webdesign11.jpg',
      youtubeId: '4P3OCq05TOE',
      tags: ['웹디자인개발기능사', '레이아웃', 'C-3'],
      description: '웹디자인개발기능사 레이아웃 C-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-11T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-4)',
      slug: toSlug('webdesign2025 layout C4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign12.tsx',
      images: 'webdesign12.jpg',
      youtubeId: 'Va0pu-lSE84',
      tags: ['웹디자인개발기능사', '레이아웃', 'C-4'],
      description: '웹디자인개발기능사 레이아웃 C-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-12T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(D-1)',
      slug: toSlug('webdesign2025 layout D1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign13.tsx',
      images: 'webdesign13.jpg',
      youtubeId: 'Qr4h-u1V1Zk',
      tags: ['웹디자인개발기능사', '레이아웃', 'D-1'],
      description: '웹디자인개발기능사 레이아웃 D-1유형 연습 강의입니다.',
      contents: 'Qr4h-u1V1Zk',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-13T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(D-2)',
      slug: toSlug('webdesign2025 layout D2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign14.tsx',
      images: 'webdesign14.jpg',
      youtubeId: 'X1VjHBmbY00',
      tags: ['웹디자인개발기능사', '레이아웃', 'D-2'],
      description: '웹디자인개발기능사 레이아웃 D-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-14T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(D-3)',
      slug: toSlug('webdesign2025 layout D3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign15.tsx',
      images: 'webdesign15.jpg',
      youtubeId: 'wq5e3T1OumU',
      tags: ['웹디자인개발기능사', '레이아웃', 'D-3'],
      description: '웹디자인개발기능사 레이아웃 D-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-15T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(D-4)',
      slug: toSlug('webdesign2025 layout D4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign16.tsx',
      images: 'webdesign16.jpg',
      youtubeId: 'sVQ7FhqGStY',
      tags: ['웹디자인개발기능사', '레이아웃', 'D-4'],
      description: '웹디자인개발기능사 레이아웃 D-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-16T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(E-1)',
      slug: toSlug('webdesign2025 layout E1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign17.tsx',
      images: 'webdesign17.jpg',
      youtubeId: 'FyLy8W5Fb1w',
      tags: ['웹디자인개발기능사', '레이아웃', 'E-1'],
      description: '웹디자인개발기능사 레이아웃 E-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-17T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(E-2)',
      slug: toSlug('webdesign2025 layout E2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign18.tsx',
      images: 'webdesign18.jpg',
      youtubeId: '7TXuozmztzk',
      tags: ['웹디자인개발기능사', '레이아웃', 'E-2'],
      description: '웹디자인개발기능사 레이아웃 E-2유형 연습 강의입니다.',
      contents: '7TXuozmztzk',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-18T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(E-3)',
      slug: toSlug('webdesign2025 layout E3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign19.tsx',
      images: 'webdesign19.jpg',
      youtubeId: 'hF86cjm4r_I',
      tags: ['웹디자인개발기능사', '레이아웃', 'E-3'],
      description: '웹디자인개발기능사 레이아웃 E-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-19T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(E-4)',
      slug: toSlug('webdesign2025 layout E4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign20.tsx',
      images: 'webdesign20.jpg',
      youtubeId: '30fbC51EgKI',
      tags: ['웹디자인개발기능사', '레이아웃', 'E-4'],
      description: '웹디자인개발기능사 레이아웃 E-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-20T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(F-1)',
      slug: toSlug('webdesign2025 layout F1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign21.tsx',
      images: 'webdesign21.jpg',
      youtubeId: 'q4Zbw0apbZ4',
      tags: ['웹디자인개발기능사', '레이아웃', 'F-1'],
      description: '웹디자인개발기능사 레이아웃 F-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-21T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(F-2)',
      slug: toSlug('webdesign2025 layout F2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign22.tsx',
      images: 'webdesign22.jpg',
      youtubeId: '1eW5Hxbh2F4',
      tags: ['웹디자인개발기능사', '레이아웃', 'F-2'],
      description: '웹디자인개발기능사 레이아웃 F-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-22T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(F-3)',
      slug: toSlug('webdesign2025 layout F3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign23.tsx',
      images: 'webdesign23.jpg',
      youtubeId: '4jhmtiVbMxU',
      tags: ['웹디자인개발기능사', '레이아웃', 'F-3'],
      description: '웹디자인개발기능사 레이아웃 F-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-23T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(F-4)',
      slug: toSlug('webdesign2025 layout F4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign24.tsx',
      images: 'webdesign24.jpg',
      youtubeId: 'Vg9ATRn1O5k',
      tags: ['웹디자인개발기능사', '레이아웃', 'F-4'],
      description: '웹디자인개발기능사 레이아웃 F-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-24T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-1)',
      slug: toSlug('webdesign2025 menu M1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign25.tsx',
      images: 'webdesign25.jpg',
      youtubeId: 'r6G4hGdikBA',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-25T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-2)',
      slug: toSlug('webdesign2025 menu M2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign26.tsx',
      images: 'webdesign26.jpg',
      youtubeId: 'NsS5uzHVjOs',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-26T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-3)',
      slug: toSlug('webdesign2025 menu M3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign27.tsx',
      images: 'webdesign27.jpg',
      youtubeId: '-kPV1X1LepY',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-27T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-4)',
      slug: toSlug('webdesign2025 menu M4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign28.tsx',
      images: 'webdesign28.jpg',
      youtubeId: '-tid_tvfXe8',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-28T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-5)',
      slug: toSlug('webdesign2025 menu M5'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign29.tsx',
      images: 'webdesign29.jpg',
      youtubeId: 'koXQRjxb4v8',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-5유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-29T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-6)',
      slug: toSlug('webdesign2025 menu M6'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign30.tsx',
      images: 'webdesign30.jpg',
      youtubeId: 'epRQNngMmng',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-6유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-30T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-7)',
      slug: toSlug('webdesign2025 menu M7'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign31.tsx',
      images: 'webdesign31.jpg',
      youtubeId: 'xZTv_rjZlCI',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-7유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-05-31T00:00:00Z'),
    },
    {
      title: '01. GSAP Parallax Effect : 기본 애니메이션',
      slug: toSlug('GSAP Parallax Effect01'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect01.tsx',
      images: 'gsap-parallax-effect01.jpg',
      youtubeId: '_rAAY_Zp4FI',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 기본 애니메이션 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-01T00:00:00Z'),
    },
    {
      title: '02. GSAP Parallax Effect : Pin 애니메이션',
      slug: toSlug('GSAP Parallax Effect02'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect02.tsx',
      images: 'gsap-parallax-effect02.jpg',
      youtubeId: 'T9kkvtHaq8E',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : Pin 애니메이션 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-02T00:00:00Z'),
    },
    {
      title: '03. GSAP Parallax Effect : Pin 배경 고정하기',
      slug: toSlug('GSAP Parallax Effect03'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect03.tsx',
      images: 'gsap-parallax-effect03.jpg',
      youtubeId: 'bP7iGE3YKOU',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : Pin 배경 고정하기 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-03T00:00:00Z'),
    },
    {
      title: '04. GSAP Parallax Effect : 이질감 효과',
      slug: toSlug('GSAP Parallax Effect04'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect04.tsx',
      images: 'gsap-parallax-effect04.jpg',
      youtubeId: 'neBcJlgfu_o',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 이질감 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-04T00:00:00Z'),
    },
    {
      title: '05. GSAP Parallax Effect : 나타나기 효과',
      slug: toSlug('GSAP Parallax Effect05'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect05.tsx',
      images: 'gsap-parallax-effect05.jpg',
      youtubeId: '9lnfRXTXzL0',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 나타나기 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-05T00:00:00Z'),
    },
    {
      title: '06. GSAP Parallax Effect : 텍스트 효과',
      slug: toSlug('GSAP Parallax Effect06'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect06.tsx',
      images: 'gsap-parallax-effect06.jpg',
      youtubeId: 'gzJnKZGsB-Y',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 텍스트 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-06T00:00:00Z'),
    },
    {
      title: '07. GSAP Parallax Effect : 배경색 효과',
      slug: toSlug('GSAP Parallax Effect07'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect07.tsx',
      images: 'gsap-parallax-effect07.jpg',
      youtubeId: 'kE0QRWPBVKs',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 배경색 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-07T00:00:00Z'),
    },
    {
      title: '08. GSAP Parallax Effect : 진행바 효과',
      slug: toSlug('GSAP Parallax Effect08'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect08.tsx',
      images: 'gsap-parallax-effect08.jpg',
      youtubeId: 'pLgDSor_27g',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 진행바 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-08T00:00:00Z'),
    },
    {
      title: '09. GSAP Parallax Effect : 메뉴 이동 효과',
      slug: toSlug('GSAP Parallax Effect09'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect09.tsx',
      images: 'gsap-parallax-effect09.jpg',
      youtubeId: 'd5xSXS1UZFY',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 메뉴 이동 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-09T00:00:00Z'),
    },
    {
      title: '10. GSAP Parallax Effect : 메뉴 축소 효과',
      slug: toSlug('GSAP Parallax Effect10'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect10.tsx',
      images: 'gsap-parallax-effect10.jpg',
      youtubeId: 'Z2NeyjasCdY',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 메뉴 축소 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-10T00:00:00Z'),
    },
    {
      title: '11. GSAP Parallax Effect : 메뉴 숨기기 효과',
      slug: toSlug('GSAP Parallax Effect11'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect11.tsx',
      images: 'gsap-parallax-effect11.jpg',
      youtubeId: 'Z2NeyjasCdY',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 메뉴 숨기기 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-11T00:00:00Z'),
    },
    {
      title: '12. GSAP Parallax Effect : 가로 효과',
      slug: toSlug('GSAP Parallax Effect12'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect12.tsx',
      images: 'gsap-parallax-effect12.jpg',
      youtubeId: 'DCtCgE08E8I',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 가로 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-12T00:00:00Z'),
    },
    {
      title: '13. GSAP Parallax Effect : 가로/세로 효과',
      slug: toSlug('GSAP Parallax Effect13'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect13.tsx',
      images: 'gsap-parallax-effect13.jpg',
      youtubeId: 'YPzwvzFfCfU',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 가로/세로 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-13T00:00:00Z'),
    },
    {
      title: '14. GSAP Parallax Effect : 가로/세로 나타나기 효과',
      slug: toSlug('GSAP Parallax Effect14'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect14.tsx',
      images: 'gsap-parallax-effect14.jpg',
      youtubeId: 'puCe3ollwTg',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 가로/세로 나타나기 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-14T00:00:00Z'),
    },
    {
      title: '15. GSAP Parallax Effect : 스무스 효과',
      slug: toSlug('GSAP Parallax Effect15'),
      category: 'lecture',
      subCategory: 'gsap-parallax-effect',
      components: 'gsap-parallax-effect15.tsx',
      images: 'gsap-parallax-effect15.jpg',
      youtubeId: 'tMsFs6GoXmg',
      tags: ['gsap', 'parallax', 'scrollTrigger'],
      description: 'GSAP Parallax Effect : 스무스 효과 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      likes: [],
      reviews: [],
      createdAt: new Date('2025-06-15T00:00:00Z'),
    },
  ],
}

export default inputData
