import { Data } from './types'

const data: Data = {
  menuData: [
    {
      label: 'Lecture',
      card: {
        title: '강의',
        description: '체계적으로 배우는 강의 커리큘럼 처음 코딩을 한다면',
        iconCount: 1,
        icon: 'BookMarked',
        href: '/lecture',
        buttonText: 'Learn',
      },
      items: [
        {
          title: '웹디자인개발기능사',
          description: '코딩이 처음이라면! 이것부터 따자!',
          href: '/lecture/webdesign2025',
        },
        {
          title: '타입스크립트',
          description: '자바스크립트와 타입스트립트를 동시에 공부합니다.',
          href: '/lecture/typescript',
        },
      ],
    },
    {
      label: 'Tutorial',
      card: {
        title: '튜토리얼',
        description: '따라하면 실력이 는다. 재미와 함께 배우는 코딩',
        iconCount: 2,
        icon: 'BookUser',
        href: '/tutorial',
        buttonText: 'Learn',
      },
      items: [
        {
          title: 'CSS Animation',
          description: 'CSS를 활용한 UI/UX 애니메이션',
          href: '/tutorial/css-animation',
        },
        {
          title: 'GSAP Animation',
          description: '웹 애니메이션과 인터랙티브 UI 개발',
          href: '/tutorial/gsap-animation',
        },
      ],
    },
    {
      label: 'Reference',
      card: {
        title: '레퍼런스',
        description: '기본적인 개념을 배우는 곳. 기본은 여기서 익히자!',
        iconCount: 3,
        icon: 'PencilRuler',
        href: '/reference',
        buttonText: 'Learn',
      },
      items: [
        {
          title: 'HTML',
          description: 'HTML의 기본 개념을 익힙니다.',
          href: '/reference/html',
        },
        {
          title: 'CSS',
          description: 'CSS의 기본 개념을 익힙니다.',
          href: '/reference/css',
        },
        {
          title: 'JAVASCRIPT',
          description: 'JAVASCRIPT의 기본 개념을 익힙니다.',
          href: '/reference/javascript',
        },
      ],
    },
    {
      label: 'Inspiration',
      card: {
        title: '인스퍼레이션',
        description: '코딩과 관련된 인스퍼레이션은 여기서 확인하자!',
        iconCount: 4,
        icon: 'Sparkles',
        href: '/inspiration',
        buttonText: 'Explore',
      },
      items: [
        {
          title: 'SITE 인스퍼레이션',
          description: '웹사이트 디자인 사례 모음.',
          href: '/inspiration/site',
        },
        {
          title: 'TUTORIAL 인스퍼레이션',
          description: '다양한 웹 개발 학습 자료.',
          href: '/inspiration/tutorial',
        },
      ],
    },
  ],
  HtmlDocs: [
    { slug: 'a', title: '<a>' },
    { slug: 'abbr', title: '<abbr>' },
    { slug: 'address', title: '<address>' },
    { slug: 'article', title: '<article>' },
    { slug: 'aside', title: '<aside>' },
    { slug: 'audio', title: '<audio>' },
    { slug: 'b', title: '<b>' },
    { slug: 'base', title: '<base>' },
    { slug: 'blockquote', title: '<blockquote>' },
    { slug: 'body', title: '<body>' },
    { slug: 'br', title: '<br>' },
    { slug: 'button', title: '<button>' },
    { slug: 'canvas', title: '<canvas>' },
    { slug: 'caption', title: '<caption>' },
    { slug: 'cite', title: '<cite>' },
    { slug: 'code', title: '<code>' },
    { slug: 'col', title: '<col>' },
    { slug: 'colgroup', title: '<colgroup>' },
    { slug: 'del', title: '<del>' },
    { slug: 'details', title: '<details>' },
    { slug: 'div', title: '<div>' },
    { slug: 'dl', title: '<dl>' },
    { slug: 'dt', title: '<dt>' },
    { slug: 'dd', title: '<dd>' },
    { slug: 'em', title: '<em>' },
    { slug: 'embed', title: '<embed>' },
    { slug: 'fieldset', title: '<fieldset>' },
    { slug: 'figcaption', title: '<figcaption>' },
    { slug: 'figure', title: '<figure>' },
    { slug: 'footer', title: '<footer>' },
    { slug: 'form', title: '<form>' },
    { slug: 'h1', title: '<h1>' },
    { slug: 'h2', title: '<h2>' },
    { slug: 'h3', title: '<h3>' },
    { slug: 'h4', title: '<h4>' },
    { slug: 'h5', title: '<h5>' },
    { slug: 'h6', title: '<h6>' },
    { slug: 'head', title: '<head>' },
    { slug: 'header', title: '<header>' },
    { slug: 'hr', title: '<hr>' },
    { slug: 'html', title: '<html>' },
    { slug: 'i', title: '<i>' },
    { slug: 'iframe', title: '<iframe>' },
    { slug: 'img', title: '<img>' },
    { slug: 'input', title: '<input>' },
    { slug: 'ins', title: '<ins>' },
    { slug: 'kbd', title: '<kbd>' },
    { slug: 'label', title: '<label>' },
    { slug: 'legend', title: '<legend>' },
    { slug: 'li', title: '<li>' },
    { slug: 'link', title: '<link>' },
    { slug: 'main', title: '<main>' },
    { slug: 'mark', title: '<mark>' },
    { slug: 'meta', title: '<meta>' },
    { slug: 'nav', title: '<nav>' },
    { slug: 'noscript', title: '<noscript>' },
    { slug: 'object', title: '<object>' },
    { slug: 'ol', title: '<ol>' },
    { slug: 'optgroup', title: '<optgroup>' },
    { slug: 'option', title: '<option>' },
    { slug: 'output', title: '<output>' },
    { slug: 'p', title: '<p>' },
    { slug: 'picture', title: '<picture>' },
    { slug: 'pre', title: '<pre>' },
    { slug: 'progress', title: '<progress>' },
    { slug: 'q', title: '<q>' },
    { slug: 's', title: '<s>' },
    { slug: 'script', title: '<script>' },
    { slug: 'section', title: '<section>' },
    { slug: 'select', title: '<select>' },
    { slug: 'small', title: '<small>' },
    { slug: 'source', title: '<source>' },
    { slug: 'span', title: '<span>' },
    { slug: 'strong', title: '<strong>' },
    { slug: 'style', title: '<style>' },
    { slug: 'sub', title: '<sub>' },
    { slug: 'summary', title: '<summary>' },
    { slug: 'sup', title: '<sup>' },
    { slug: 'svg', title: '<svg>' },
    { slug: 'table', title: '<table>' },
    { slug: 'tbody', title: '<tbody>' },
    { slug: 'td', title: '<td>' },
    { slug: 'template', title: '<template>' },
    { slug: 'textarea', title: '<textarea>' },
    { slug: 'tfoot', title: '<tfoot>' },
    { slug: 'th', title: '<th>' },
    { slug: 'thead', title: '<thead>' },
    { slug: 'time', title: '<time>' },
    { slug: 'title', title: '<title>' },
    { slug: 'tr', title: '<tr>' },
    { slug: 'u', title: '<u>' },
    { slug: 'ul', title: '<ul>' },
    { slug: 'var', title: '<var>' },
    { slug: 'video', title: '<video>' },
    { slug: 'wbr', title: '<wbr>' },
  ],
  CssDocs: [
    'accent-color',
    'align-content',
    'min-height',
    'max-height',
    'height',
    'min-width',
    'max-width',
    'width',
    'border-inline-end-width',
    'border-inline-end-style',
    'border-inline-end-color',
    'border-inline-end',
    'border-inline-start-width',
    'border-inline-start-style',
    'border-inline-start-color',
    'border-inline-start',
    'border-inline-width',
    'border-inline-style',
    'border-inline-color',
    'border-inline',
    'border-block-end-width',
    'border-block-end-style',
    'border-block-end-color',
    'border-block-end',
    'border-block-start-width',
    'border-block-start-style',
    'border-block-start-color',
    'border-block-start',
    'border-block-width',
    'border-block-style',
  ],
}

export default data
