import bcrypt from 'bcryptjs'
import { InputData } from './types'
import { toSlug } from './utils'

const inputData: InputData = {
  users: [
    {
      name: 'webstoryboy',
      email: 'webstoryboy@naver.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'Admin',
      image: '/face/face01.jpg',
      visitCount: 0,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Jane Smith',
      email: 'janesmith@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face02.jpg',
      visitCount: 4,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Alice Johnson',
      email: 'alicej@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face03.jpg',
      visitCount: 50,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Bob Williams',
      email: 'bobw@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face04.jpg',
      visitCount: 60,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Charlie Brown',
      email: 'charlieb@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face05.jpg',
      visitCount: 3,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'David Clark',
      email: 'davidc@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face06.jpg',
      visitCount: 4,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Emma White',
      email: 'emmaw@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face07.jpg',
      visitCount: 5,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Frank Green',
      email: 'frankg@example.com',
      emailVerified: true,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face08.jpg',
      visitCount: 2,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Grace Hall',
      email: 'graceh@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face09.jpg',
      visitCount: 4,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Henry Young',
      email: 'henryy@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face10.jpg',
      visitCount: 5,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Isabella Lee',
      email: 'isabellal@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face01.jpg',
      visitCount: 50,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Jack Wilson',
      email: 'jackw@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face02.jpg',
      visitCount: 100,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Karen Martinez',
      email: 'karenm@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face03.jpg',
      visitCount: 12,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Liam Davis',
      email: 'liamd@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face04.jpg',
      visitCount: 8,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Mia Thompson',
      email: 'miat@example.com',
      emailVerified: true,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face05.jpg',
      visitCount: 25,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Noah Garcia',
      email: 'noahg@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face06.jpg',
      visitCount: 30,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Olivia Martinez',
      email: 'oliviam@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face07.jpg',
      visitCount: 18,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Sophia Rodriguez',
      email: 'sophiar@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face08.jpg',
      visitCount: 22,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'William Hernandez',
      email: 'williamh@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face09.jpg',
      visitCount: 9,
      verificationToken: null,
      isActive: true,
    },
    {
      name: 'Ava Lopez',
      email: 'avalopez@example.com',
      emailVerified: false,
      password: bcrypt.hashSync('123456', 10),
      role: 'User',
      image: '/face/face10.jpg',
      visitCount: 15,
      verificationToken: null,
      isActive: true,
    },
  ],
  posts: [
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-1)',
      slug: toSlug('webdesign layout A1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign01',
      images: 'webdesign01.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'A-1'],
      description: '웹디자인개발기능사 레이아웃 A-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-01T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-2)',
      slug: toSlug('webdesign layout A2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign02',
      images: 'webdesign02.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'A-2'],
      description: '웹디자인개발기능사 레이아웃 A-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-02T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-3)',
      slug: toSlug('webdesign layout A3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign03',
      images: 'webdesign03.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'A-3'],
      description: '웹디자인개발기능사 레이아웃 A-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-03T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(A-4)',
      slug: toSlug('webdesign layout A4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign04',
      images: 'webdesign04.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'A-4'],
      description: '웹디자인개발기능사 레이아웃 A-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-04T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-1)',
      slug: toSlug('webdesign layout B1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign05',
      images: 'webdesign05.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'B-1'],
      description: '웹디자인개발기능사 레이아웃 B-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-05T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-2)',
      slug: toSlug('webdesign layout B2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign06',
      images: 'webdesign06.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'B-2'],
      description: '웹디자인개발기능사 레이아웃 B-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-06T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-3)',
      slug: toSlug('webdesign layout B3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign07',
      images: 'webdesign07.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'B-3'],
      description: '웹디자인개발기능사 레이아웃 B-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-07T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(B-4)',
      slug: toSlug('webdesign layout B4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign08',
      images: 'webdesign08.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'B-4'],
      description: '웹디자인개발기능사 레이아웃 B-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-08T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-1)',
      slug: toSlug('webdesign layout C1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign09',
      images: 'webdesign09.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'C-1'],
      description: '웹디자인개발기능사 레이아웃 C-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-09T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-2)',
      slug: toSlug('webdesign layout C2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign10',
      images: 'webdesign10.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'C-2'],
      description: '웹디자인개발기능사 레이아웃 C-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-10T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-3)',
      slug: toSlug('webdesign layout C3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign11',
      images: 'webdesign11.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'C-3'],
      description: '웹디자인개발기능사 레이아웃 C-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-11T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(C-4)',
      slug: toSlug('webdesign layout C4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign12',
      images: 'webdesign12.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'C-4'],
      description: '웹디자인개발기능사 레이아웃 C-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-12T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(D-1)',
      slug: toSlug('webdesign layout D1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign13',
      images: 'webdesign13.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'D-1'],
      description: '웹디자인개발기능사 레이아웃 D-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-13T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(D-2)',
      slug: toSlug('webdesign layout D2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign14',
      images: 'webdesign14.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'D-2'],
      description: '웹디자인개발기능사 레이아웃 D-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-14T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(D-3)',
      slug: toSlug('webdesign layout D3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign15',
      images: 'webdesign15.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'D-3'],
      description: '웹디자인개발기능사 레이아웃 D-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-15T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(D-4)',
      slug: toSlug('webdesign layout D4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign16',
      images: 'webdesign16.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'D-4'],
      description: '웹디자인개발기능사 레이아웃 D-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-16T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(E-1)',
      slug: toSlug('webdesign layout E1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign17',
      images: 'webdesign17.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'E-1'],
      description: '웹디자인개발기능사 레이아웃 E-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-17T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(E-2)',
      slug: toSlug('webdesign layout E2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign18',
      images: 'webdesign18.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'E-2'],
      description: '웹디자인개발기능사 레이아웃 E-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-18T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(E-3)',
      slug: toSlug('webdesign layout E3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign19',
      images: 'webdesign19.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'E-3'],
      description: '웹디자인개발기능사 레이아웃 E-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-19T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(E-4)',
      slug: toSlug('webdesign layout E4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign20',
      images: 'webdesign20.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'E-4'],
      description: '웹디자인개발기능사 레이아웃 E-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-20T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(F-1)',
      slug: toSlug('webdesign layout F1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign21',
      images: 'webdesign21.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'F-1'],
      description: '웹디자인개발기능사 레이아웃 F-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-21T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(F-2)',
      slug: toSlug('webdesign layout F2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign22',
      images: 'webdesign22.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'F-2'],
      description: '웹디자인개발기능사 레이아웃 F-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-22T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(F-3)',
      slug: toSlug('webdesign layout F3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign23',
      images: 'webdesign23.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'F-3'],
      description: '웹디자인개발기능사 레이아웃 F-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-23T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 레이아웃 유형(F-4)',
      slug: toSlug('webdesign layout F4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign24',
      images: 'webdesign24.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '레이아웃', 'F-4'],
      description: '웹디자인개발기능사 레이아웃 F-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-01-24T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-1)',
      slug: toSlug('webdesign menu M1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign25',
      images: 'webdesign25.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-01T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-2)',
      slug: toSlug('webdesign menu M2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign26',
      images: 'webdesign26.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-02T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-3)',
      slug: toSlug('webdesign menu M3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign27',
      images: 'webdesign27.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-03T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-4)',
      slug: toSlug('webdesign menu M4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign28',
      images: 'webdesign28.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-04T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-5)',
      slug: toSlug('webdesign menu M5'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign29',
      images: 'webdesign29.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-5유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-05T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 메뉴 유형(M-6)',
      slug: toSlug('webdesign menu M6'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign30',
      images: 'webdesign30.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '메뉴'],
      description: '웹디자인개발기능사 레이아웃 M-6유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-06T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 슬라이드 유형(S-1)',
      slug: toSlug('webdesign slide S1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign31',
      images: 'webdesign31.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '슬라이드'],
      description: '웹디자인개발기능사 슬라이드 S-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-07T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 슬라이드 유형(S-2)',
      slug: toSlug('webdesign slide S2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign32',
      images: 'webdesign32.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '슬라이드'],
      description: '웹디자인개발기능사 슬라이드 S-2유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-08T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 슬라이드 유형(S-3)',
      slug: toSlug('webdesign slide S3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign33',
      images: 'webdesign33.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '슬라이드'],
      description: '웹디자인개발기능사 슬라이드 S-3유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-09T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 슬라이드 유형(S-4)',
      slug: toSlug('webdesign slide S4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign34',
      images: 'webdesign34.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '슬라이드'],
      description: '웹디자인개발기능사 슬라이드 S-4유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-10T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 슬라이드 유형(S-5)',
      slug: toSlug('webdesign slide S5'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign35',
      images: 'webdesign35.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '슬라이드'],
      description: '웹디자인개발기능사 슬라이드 S-5유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-11T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 슬라이드 유형(S-6)',
      slug: toSlug('webdesign slide S6'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign36',
      images: 'webdesign36.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '슬라이드'],
      description: '웹디자인개발기능사 슬라이드 S-6유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-12T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 탭메뉴 유형(T-1)',
      slug: toSlug('webdesign tap T1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign37',
      images: 'webdesign37.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '탭메뉴'],
      description: '웹디자인개발기능사 탭메뉴 T-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-13T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 팝업 유형(P-1)',
      slug: toSlug('webdesign popup P1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesign38',
      images: 'webdesign38.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '스크립트', '팝업'],
      description: '웹디자인개발기능사 팝업 P-1유형 연습 강의입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-02-13T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 A-1 - JUST 쇼핑몰',
      slug: toSlug('webdesign practical a1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignA1',
      images: 'webdesignA1.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', 'JUST 쇼핑몰'],
      description: '웹디자인개발기능사 실기 JUST 쇼핑몰 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-01T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 A-2 - Green 복지 재단',
      slug: toSlug('webdesign practical a2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignA2',
      images: 'webdesignA2.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', 'Green 복지 재단'],
      description: '웹디자인개발기능사 실기 Green 복지 재단 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-02T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 A-3 - 강원 천문대',
      slug: toSlug('webdesign practical a3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignA3',
      images: 'webdesignA3.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '강원 천문대'],
      description: '웹디자인개발기능사 실기 강원 천문대 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-03T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 A-4 - 유진 건설',
      slug: toSlug('webdesign practical a4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignA4',
      images: 'webdesignA4.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '유진 건설'],
      description: '웹디자인개발기능사 실기 유진 건설 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-04T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 B-1 - 대한 은행',
      slug: toSlug('webdesign practical b1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignB1',
      images: 'webdesignB1.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '대한 은행'],
      description: '웹디자인개발기능사 실기 대한 은행 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-05T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 B-2 - 대한 투어',
      slug: toSlug('webdesign practical b2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignB2',
      images: 'webdesignB2.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '대한 투어'],
      description: '웹디자인개발기능사 실기 대한 투어 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-06T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 B-3 - 세계의 미술작품',
      slug: toSlug('webdesign practical b3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignB3',
      images: 'webdesignB3.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '세계의 미술작품'],
      description: '웹디자인개발기능사 실기 세계의 미술작품 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-07T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 B-4 - 산업 대학교',
      slug: toSlug('webdesign practical b4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignB4',
      images: 'webdesignB4.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '산업 대학교'],
      description: '웹디자인개발기능사 실기 산업 대학교 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-08T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 C-1 - 해운대 빛축제',
      slug: toSlug('webdesign practical c1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignC1',
      images: 'webdesignC1.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '해운대 빛축제'],
      description: '웹디자인개발기능사 실기 해운대 빛축제 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-09T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 C-2 - 부여 가을연꽃축제',
      slug: toSlug('webdesign practical c2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignC2',
      images: 'webdesignC2.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '부여 가을연꽃축제'],
      description: '웹디자인개발기능사 실기 부여 가을연꽃축제 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-10T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 C-3 - 남도 맛기행 축제',
      slug: toSlug('webdesign practical c3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignC3',
      images: 'webdesignC3.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '남도 맛기행 축제'],
      description: '웹디자인개발기능사 실기 남도 맛기행 축제 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-11T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 C-4 - Vallery Festival',
      slug: toSlug('webdesign practical c4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignC4',
      images: 'webdesignC4.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', 'Vallery Festival'],
      description: '웹디자인개발기능사 실기 Vallery Festival 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-12T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 D-1 - 조이 컨트리 클럽',
      slug: toSlug('webdesign practical d1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignD1',
      images: 'webdesignD1.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '조이 컨트리 클럽'],
      description: '웹디자인개발기능사 실기 조이 컨트리 클럽 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-13T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 D-2 - 서울 구석구석',
      slug: toSlug('webdesign practical d2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignD2',
      images: 'webdesignD2.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '서울 구석구석'],
      description: '웹디자인개발기능사 실기 서울 구석구석 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-14T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 D-3 - 푸른 마을',
      slug: toSlug('webdesign practical d3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignD3',
      images: 'webdesignD3.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '푸른 마을'],
      description: '웹디자인개발기능사 실기 푸른 마을 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-15T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 D-4 - 리빙샵 아울렛',
      slug: toSlug('webdesign practical d4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignD4',
      images: 'webdesignD4.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '리빙샵 아울렛'],
      description: '웹디자인개발기능사 실기 리빙샵 아울렛 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-16T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 E-1 - 김치 이야기',
      slug: toSlug('webdesign practical e1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignE1',
      images: 'webdesignE1.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '김치 이야기'],
      description: '웹디자인개발기능사 실기 김치 이야기 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-17T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 E-2 - 역사 박물관',
      slug: toSlug('webdesign practical e2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignE2',
      images: 'webdesignE2.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '역사 박물관'],
      description: '웹디자인개발기능사 실기 역사 박물관 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-18T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 E-3 - 영상 박물관',
      slug: toSlug('webdesign practical e3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignE3',
      images: 'webdesignE3.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '영상 박물관'],
      description: '웹디자인개발기능사 실기 영상 박물관 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-19T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 E-4 - 철길 마을',
      slug: toSlug('webdesign practical e4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignE4',
      images: 'webdesignE4.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '철길 마을'],
      description: '웹디자인개발기능사 실기 철길 마을 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-20T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 F-1 - 주식회사 기능건설',
      slug: toSlug('webdesign practical f1'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignF1',
      images: 'webdesignF1.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '주식회사 기능건설'],
      description: '웹디자인개발기능사 실기 주식회사 기능건설 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-21T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 F-2 - 기능 대학교',
      slug: toSlug('webdesign practical f2'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignF2',
      images: 'webdesignF2.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '기능 대학교'],
      description: '웹디자인개발기능사 실기 기능 대학교 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-22T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 F-3 - 오픈 뱅킹',
      slug: toSlug('webdesign practical f3'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignF3',
      images: 'webdesignF3.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '오픈 뱅킹'],
      description: '웹디자인개발기능사 실기 오픈 뱅킹 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-23T00:00:00Z'),
    },
    {
      title: '웹디자인개발기능사 실기 F-4 - 하이 글로벌 컴퍼니',
      slug: toSlug('webdesign practical f4'),
      category: 'lecture',
      subCategory: 'webdesign2025',
      components: 'webdesignF4',
      images: 'webdesignF4.jpg',
      youtubeId: '',
      tags: ['웹디자인개발기능사', '실기', '하이 글로벌 컴퍼니'],
      description: '웹디자인개발기능사 실기 하이 글로벌 컴퍼니 예제입니다.',
      contents: '',
      isPublished: true,
      author: '웹스토리보이',
      numReviews: 0,
      numViews: 0,
      numLikes: 0,
      reviews: [],
      createdAt: new Date('2025-03-24T00:00:00Z'),
    },
  ],
}

export default inputData
