import { Data } from './types'

const data: Data = {
  koreaMenu: [
    {
      title: 'Melon',
      ko: '멜론',
      href: '/korea/melon',
      description: '국내 최대 음원 플랫폼, 다양한 장르와 최신 음악 제공',
      url: 'https://www.melon.com/chart/index.htm',
    },
    {
      title: 'Genie',
      ko: '지니',
      href: '/korea/genie',
      description: '지니뮤직, 감성적인 플레이리스트와 고음질 음원 서비스',
      url: 'https://www.genie.co.kr/chart/top200?ditc=D&ymd=20241105&hh=10&rtm=Y&pg=1',
    },
    {
      title: 'Bugs',
      ko: '벅스뮤직',
      href: '/korea/bugs',
      description: '벅스뮤직, 고음질 스트리밍과 다양한 음악 콘텐츠 제공',
      url: 'https://music.bugs.co.kr/chart',
    },
    {
      title: 'Flo',
      ko: '플로우',
      href: '/korea/flo',
      description: '개인 맞춤형 음악 추천, 실시간 차트 및 다양한 플레이리스트',
      url: 'https://www.music-flo.com/browse',
    },
    {
      title: 'Vibe',
      ko: '바이브',
      href: '/korea/vibe',
      description: 'AI 기반 음악 추천 플랫폼, 나만의 맞춤형 선곡 서비스',
      url: 'https://vibe.naver.com/chart/total',
    },
  ],
  worldMenu: [
    {
      title: 'Youtube',
      href: '/world/youtube',
      description: '국내 최대 음원 플랫폼, 다양한 장르와 최신 음악 제공',
    },
    {
      title: 'Apple',
      href: '/world/apple',
      description: '국내 최대 음원 플랫폼, 다양한 장르와 최신 음악 제공',
    },
  ],
  youtubeCountry: [
    {
      name: 'global',
      nameKorean: '글로벌',
      icon: '🌏',
      url: 'https://charts.youtube.com/charts/TopSongs/global/weekly',
    },
    {
      name: 'argentina',
      nameKorean: '아르헨티나',
      icon: '🇦🇷',
      url: 'https://charts.youtube.com/charts/TopSongs/ar/weekly',
    },
    {
      name: 'australia',
      nameKorean: '호주',
      icon: '🇦🇺',
      url: 'https://charts.youtube.com/charts/TopSongs/au/weekly',
    },
    {
      name: 'austria',
      nameKorean: '오스트리아',
      icon: '🇦🇹',
      url: 'https://charts.youtube.com/charts/TopSongs/at/weekly',
    },
    {
      name: 'belgium',
      nameKorean: '벨기에',
      icon: '🇧🇪',
      url: 'https://charts.youtube.com/charts/TopSongs/be/weekly',
    },
    {
      name: 'bolivia',
      nameKorean: '볼리비아',
      icon: '🇧🇴',
      url: 'https://charts.youtube.com/charts/TopSongs/be/weekly',
    },
    {
      name: 'brazil',
      nameKorean: '브라질',
      icon: '🇧🇷',
      url: 'https://charts.youtube.com/charts/TopSongs/br/weekly',
    },
    {
      name: 'canada',
      nameKorean: '캐나다',
      icon: '🇨🇦',
      url: 'https://charts.youtube.com/charts/TopSongs/ca/weekly',
    },
    {
      name: 'chile',
      nameKorean: '칠레',
      icon: '🇨🇱',
      url: 'https://charts.youtube.com/charts/TopSongs/cl/weekly',
    },
    {
      name: 'colombia',
      nameKorean: '콜롬비아',
      icon: '🇨🇴',
      url: 'https://charts.youtube.com/charts/TopSongs/co/weekly',
    },
    {
      name: 'costa-rica',
      nameKorean: '코스타리카',
      icon: '🇨🇷',
      url: 'https://charts.youtube.com/charts/TopSongs/cr/weekly',
    },
    {
      name: 'czechia',
      nameKorean: '체코',
      icon: '🇨🇿',
      url: 'https://charts.youtube.com/charts/TopSongs/cz/weekly',
    },
    {
      name: 'denmark',
      nameKorean: '덴마크',
      icon: '🇩🇰',
      url: 'https://charts.youtube.com/charts/TopSongs/dk/weekly',
    },
    {
      name: 'dominican_republic',
      nameKorean: '도미니카 공화국',
      icon: '🇩🇴',
      url: 'https://charts.youtube.com/charts/TopSongs/do/weekly',
    },
    {
      name: 'ecuador',
      nameKorean: '에콰도르',
      icon: '🇪🇨',
      url: 'https://charts.youtube.com/charts/TopSongs/ec/weekly',
    },
    {
      name: 'egypt',
      nameKorean: '이집트',
      icon: '🇪🇬',
      url: 'https://charts.youtube.com/charts/TopSongs/eg/weekly',
    },
    {
      name: 'el-salvador',
      nameKorean: '엘살바도르',
      icon: '🇸🇻',
      url: 'https://charts.youtube.com/charts/TopSongs/sv/weekly',
    },
    {
      name: 'estonia',
      nameKorean: '에스토니아',
      icon: '🇪🇪',
      url: 'https://charts.youtube.com/charts/TopSongs/ee/weekly',
    },
    {
      name: 'finland',
      nameKorean: '핀란드',
      icon: '🇫🇮',
      url: 'https://charts.youtube.com/charts/TopSongs/fi/weekly',
    },
    {
      name: 'france',
      nameKorean: '프랑스',
      icon: '🇫🇷',
      url: 'https://charts.youtube.com/charts/TopSongs/fr/weekly',
    },
    {
      name: 'germany',
      nameKorean: '독일',
      icon: '🇩🇪',
      url: 'https://charts.youtube.com/charts/TopSongs/de/weekly',
    },
    {
      name: 'guatemala',
      nameKorean: '과테말라',
      icon: '🇬🇹',
      url: 'https://charts.youtube.com/charts/TopSongs/gt/weekly',
    },
    {
      name: 'honduras',
      nameKorean: '온두라스',
      icon: '🇭🇳',
      url: 'https://charts.youtube.com/charts/TopSongs/hn/weekly',
    },
    {
      name: 'hungary',
      nameKorean: '헝가리',
      icon: '🇭🇺',
      url: 'https://charts.youtube.com/charts/TopSongs/hu/weekly',
    },
    {
      name: 'iceland',
      nameKorean: '아이슬란드',
      icon: '🇮🇸',
      url: 'https://charts.youtube.com/charts/TopSongs/is/weekly',
    },
    {
      name: 'india',
      nameKorean: '인도',
      icon: '🇮🇳',
      url: 'https://charts.youtube.com/charts/TopSongs/in/weekly',
    },
    {
      name: 'indonesia',
      nameKorean: '인도네시아',
      icon: '🇮🇩',
      url: 'https://charts.youtube.com/charts/TopSongs/id/weekly',
    },
    {
      name: 'israel',
      nameKorean: '이스라엘',
      icon: '🇮🇱',
      url: 'https://charts.youtube.com/charts/TopSongs/il/weekly',
    },
    {
      name: 'italy',
      nameKorean: '이탈리아',
      icon: '🇮🇹',
      url: 'https://charts.youtube.com/charts/TopSongs/it/weekly',
    },
    {
      name: 'japan',
      nameKorean: '일본',
      icon: '🇯🇵',
      url: 'https://charts.youtube.com/charts/TopSongs/jp/weekly',
    },
    {
      name: 'kenya',
      nameKorean: '케냐',
      icon: '🇰🇪',
      url: 'https://charts.youtube.com/charts/TopSongs/ke/weekly',
    },
    {
      name: 'luxembourg',
      nameKorean: '룩셈부르크',
      icon: '🇱🇺',
      url: 'https://charts.youtube.com/charts/TopSongs/lu/weekly',
    },
    {
      name: 'mexico',
      nameKorean: '멕시코',
      icon: '🇲🇽',
      url: 'https://charts.youtube.com/charts/TopSongs/mx/weekly',
    },
    {
      name: 'netherlands',
      nameKorean: '네덜란드',
      icon: '🇳🇱',
      url: 'https://charts.youtube.com/charts/TopSongs/nl/weekly',
    },
    {
      name: 'new-zealand',
      nameKorean: '뉴질랜드',
      icon: '🇳🇿',
      url: 'https://charts.youtube.com/charts/TopSongs/nz/weekly',
    },
    {
      name: 'nicaragua',
      nameKorean: '니카라과',
      icon: '🇳🇮',
      url: 'https://charts.youtube.com/charts/TopSongs/ni/weekly',
    },
    {
      name: 'nigeria',
      nameKorean: '나이지리아',
      icon: '🇳🇬',
      url: 'https://charts.youtube.com/charts/TopSongs/ng/weekly',
    },
    {
      name: 'norway',
      nameKorean: '노르웨이',
      icon: '🇳🇴',
      url: 'https://charts.youtube.com/charts/TopSongs/no/weekly',
    },
    {
      name: 'panama',
      nameKorean: '파나마',
      icon: '🇵🇦',
      url: 'https://charts.youtube.com/charts/TopSongs/pa/weekly',
    },
    {
      name: 'paraguay',
      nameKorean: '파라과이',
      icon: '🇵🇾',
      url: 'https://charts.youtube.com/charts/TopSongs/py/weekly',
    },
    {
      name: 'peru',
      nameKorean: '페루',
      icon: '🇵🇪',
      url: 'https://charts.youtube.com/charts/TopSongs/pe/weekly',
    },
    {
      name: 'poland',
      nameKorean: '폴란드',
      icon: '🇵🇱',
      url: 'https://charts.youtube.com/charts/TopSongs/pl/weekly',
    },
    {
      name: 'portugal',
      nameKorean: '포르투갈',
      icon: '🇵🇹',
      url: 'https://charts.youtube.com/charts/TopSongs/pt/weekly',
    },
    {
      name: 'romania',
      nameKorean: '루마니아',
      icon: '🇷🇴',
      url: 'https://charts.youtube.com/charts/TopSongs/ro/weekly',
    },
    {
      name: 'russia',
      nameKorean: '러시아',
      icon: '🇷🇺',
      url: 'https://charts.youtube.com/charts/TopSongs/ru/weekly',
    },
    {
      name: 'saudi-arabia',
      nameKorean: '사우디아라비아',
      icon: '🇸🇦',
      url: 'https://charts.youtube.com/charts/TopSongs/sa/weekly',
    },
    {
      name: 'serbia',
      nameKorean: '세르비아',
      icon: '🇷🇸',
      url: 'https://charts.youtube.com/charts/TopSongs/rs/weekly',
    },
    {
      name: 'south-africa',
      nameKorean: '남아프리카 공화국',
      icon: '🇿🇦',
      url: 'https://charts.youtube.com/charts/TopSongs/za/weekly',
    },
    {
      name: 'south-korea',
      nameKorean: '대한민국',
      icon: '🇰🇷',
      url: 'https://charts.youtube.com/charts/TopSongs/kr/weekly',
    },
    {
      name: 'spain',
      nameKorean: '스페인',
      icon: '🇪🇸',
      url: 'https://charts.youtube.com/charts/TopSongs/es/weekly',
    },
    {
      name: 'sweden',
      nameKorean: '스웨덴',
      icon: '🇸🇪',
      url: 'https://charts.youtube.com/charts/TopSongs/se/weekly',
    },
    {
      name: 'switzerland',
      nameKorean: '스위스',
      icon: '🇨🇭',
      url: 'https://charts.youtube.com/charts/TopSongs/ch/weekly',
    },
    {
      name: 'tanzania',
      nameKorean: '탄자니아',
      icon: '🇹🇿',
      url: 'https://charts.youtube.com/charts/TopSongs/tz/weekly',
    },
    {
      name: 'turkey',
      nameKorean: '튀르키예',
      icon: '🇹🇷',
      url: 'https://charts.youtube.com/charts/TopSongs/tr/weekly',
    },
    {
      name: 'uganda',
      nameKorean: '우간다',
      icon: '🇺🇬',
      url: 'https://charts.youtube.com/charts/TopSongs/ug/weekly',
    },
    {
      name: 'ukraine',
      nameKorean: '우크라이나',
      icon: '🇺🇦',
      url: 'https://charts.youtube.com/charts/TopSongs/ua/weekly',
    },
    {
      name: 'united-arab-emirates',
      nameKorean: '아랍에미리트',
      icon: '🇦🇪',
      url: 'https://charts.youtube.com/charts/TopSongs/ae/weekly',
    },
    {
      name: 'united-kingdom',
      nameKorean: '영국',
      icon: '🇬🇧',
      url: 'https://charts.youtube.com/charts/TopSongs/gb/weekly',
    },
    {
      name: 'united-states',
      nameKorean: '미국',
      icon: '🇺🇸',
      url: 'https://charts.youtube.com/charts/TopSongs/us/weekly',
    },
    {
      name: 'uruguay',
      nameKorean: '우루과이',
      icon: '🇺🇾',
      url: 'https://charts.youtube.com/charts/TopSongs/uy/weekly',
    },
    {
      name: 'zimbabwe',
      nameKorean: '짐바브웨',
      icon: '🇿🇼',
      url: 'https://charts.youtube.com/charts/TopSongs/zw/weekly',
    },
  ],
  applyCountry: [
    {
      name: 'global',
      nameKorean: '글로벌',
      icon: '🌏',
      url: 'https://music.apple.com/us/playlist/top-100-global/pl.d25f5d1181894928af76c85c967f8f31',
    },
    {
      name: 'antigua-and-barbuda',
      nameKorean: '앤티가 바부다',
      icon: '🇦🇬',
      url: 'https://music.apple.com/us/playlist/top-100-antigua-and-barbuda/pl.cca0d50798424e4e871820a03719e841',
    },
    {
      name: 'argentina',
      nameKorean: '아르헨티나',
      icon: '🇦🇷',
      url: 'https://music.apple.com/us/playlist/top-100-argentina/pl.7ae8594e422f44658e58212d876d9323',
    },
    {
      name: 'armenia',
      nameKorean: '아르메니아',
      icon: '🇦🇲',
      url: 'https://music.apple.com/us/playlist/top-100-armenia/pl.42abb2144d594137a8fb4d37a9f35b42',
    },
    {
      name: 'austria',
      nameKorean: '오스트리아',
      icon: '🇦🇺',
      url: 'https://music.apple.com/us/playlist/top-100-australia/pl.18be1cf04dfd4ffb9b6b0453e8fae8f1',
    },
    {
      name: 'azerbaijan',
      nameKorean: '아제르바이잔',
      icon: '🇦🇿',
      url: 'https://music.apple.com/us/playlist/top-100-azerbaijan/pl.ccc31c81303c405baddaaf0f5328b7f3',
    },
    {
      name: 'bahrain',
      nameKorean: '바레인',
      icon: '🇧🇭',
      url: 'https://music.apple.com/us/playlist/top-100-bahrain/pl.02a8276fa4ca40b19ac248fda4725fbb',
    },
    {
      name: 'barbados',
      nameKorean: '바베이도스',
      icon: '🇧🇧',
      url: 'https://music.apple.com/us/playlist/top-100-barbados/pl.13743dcd86174ea5b4cb6b2534637e23',
    },
    {
      name: 'belarus',
      nameKorean: '벨라루스',
      icon: '🇧🇾',
      url: 'https://music.apple.com/us/playlist/top-100-belarus/pl.50c1747c37404a9aa07acc39316f6873',
    },
    {
      name: 'belgium',
      nameKorean: '벨기에',
      icon: '🇧🇪',
      url: 'https://music.apple.com/us/playlist/top-100-belgium/pl.cefe84f7916b4cae8b21b0a78e948380',
    },
    {
      name: 'belize',
      nameKorean: '벨리즈',
      icon: '🇧🇧',
      url: 'https://music.apple.com/us/playlist/top-100-belize/pl.c6d8b5dcf6814168a4b0262628d3a317',
    },
    {
      name: 'bolivia',
      nameKorean: '볼리비아',
      icon: '🇧🇴',
      url: 'https://music.apple.com/us/playlist/top-100-bolivia/pl.cfcd547b034d47648a16fb8e2df0623f',
    },
    {
      name: 'botswana',
      nameKorean: '보츠와나',
      icon: '🇧🇼',
      url: 'https://music.apple.com/us/playlist/top-100-botswana/pl.73bb3593281444fb8ab21d58ccab4600',
    },
    {
      name: 'brazil',
      nameKorean: '브라질',
      icon: '🇧🇷',
      url: 'https://music.apple.com/us/playlist/top-100-brazil/pl.11ac7cc7d09741c5822e8c66e5c7edbb',
    },
    {
      name: 'bulgaria',
      nameKorean: '불가리아',
      icon: '🇧🇬',
      url: 'https://music.apple.com/us/playlist/top-100-bulgaria/pl.040cf0b4c7e9467eb9eed2d33e7a29d6',
    },
    {
      name: 'cambodia',
      nameKorean: '캄보디아',
      icon: '🇰🇭',
      url: 'https://music.apple.com/us/playlist/top-100-cambodia/pl.9d9ee12c7734402ab5ab0dc81911822c',
    },
    {
      name: 'cape-verde',
      nameKorean: '카보베르데',
      icon: '🇨🇻',
      url: 'https://music.apple.com/us/playlist/top-100-cape-verde/pl.917f294713a34cdeb46e67ad2a137067',
    },
    {
      name: 'chile',
      nameKorean: '칠레',
      icon: '🇨🇱',
      url: 'https://music.apple.com/us/playlist/top-100-chile/pl.81015bbbefdd46758b2c8c7065f0863e',
    },
    {
      name: 'china',
      nameKorean: '중국',
      icon: '🇨🇳',
      url: 'https://music.apple.com/us/playlist/top-100-china/pl.fde851dc95ce4ffbb74028dfd254ced5',
    },
    {
      name: 'colombia',
      nameKorean: '콜롬비아',
      icon: '🇨🇴',
      url: 'https://music.apple.com/us/playlist/top-100-colombia/pl.d116fa6286734b74acff3d38a740fe0d',
    },
    {
      name: 'costa-rica',
      nameKorean: '코스타리카',
      icon: '🇨🇷',
      url: 'https://music.apple.com/us/playlist/top-100-costa-rica/pl.7771c20fc0354f64a723ae9c11a4d5f5',
    },
    {
      name: 'cyprus',
      nameKorean: '키프로스',
      icon: '🇨🇾',
      url: 'https://music.apple.com/us/playlist/top-100-cyprus/pl.a5ae21745d1d45edacb68971746d31ae',
    },
    {
      name: 'czechia',
      nameKorean: '체코',
      icon: '🇨🇿',
      url: 'https://music.apple.com/us/playlist/top-100-czechia/pl.e447d9ba54254130a76143bf6fdfa65c',
    },
    {
      name: 'denmark',
      nameKorean: '덴마크',
      icon: '🇩🇰',
      url: 'https://music.apple.com/us/playlist/top-100-denmark/pl.d08496850bc840a4874e877177a69f9f',
    },
    {
      name: 'dominica',
      nameKorean: '도미니카',
      icon: '🇩🇲',
      url: 'https://music.apple.com/us/playlist/top-100-dominica/pl.68e6ad675521400487ea78463b39899d',
    },
    {
      name: 'dominican-republic',
      nameKorean: '도미니카 공화국',
      icon: '🇩🇴',
      url: 'https://music.apple.com/us/playlist/top-100-dominican-republic/pl.deec8b036583481782c40a2a05554b0b',
    },
    {
      name: 'ecuador',
      nameKorean: '에콰도르',
      icon: '🇪🇨',
      url: 'https://music.apple.com/us/playlist/top-100-ecuador/pl.41b0d399afea495699dbc7660994a96c',
    },
    {
      name: 'egypt',
      nameKorean: '이집트',
      icon: '🇪🇬',
      url: 'https://music.apple.com/us/playlist/top-100-egypt/pl.a0b3d0b9a2764646b59ccacdf82e3544',
    },
    {
      name: 'el-salvador',
      nameKorean: '엘살바도르',
      icon: '🇸🇻',
      url: 'https://music.apple.com/us/playlist/top-100-el-salvador/pl.9a175d1e9b1e4c81bfa7c63f28c1a79e',
    },
    {
      name: 'estonia',
      nameKorean: '에스토니아',
      icon: '🇪🇪',
      url: 'https://music.apple.com/us/playlist/top-100-estonia/pl.054734b06c7742a985805f45a283bcb4',
    },
    {
      name: 'eswatini',
      nameKorean: '에스와티니',
      icon: '🇸🇿',
      url: 'https://music.apple.com/us/playlist/top-100-micronesia/pl.bee910bc105b43c28eed7d20e4e09a8c',
    },
    {
      name: 'fiji',
      nameKorean: '피지',
      icon: '🇫🇯',
      url: 'https://music.apple.com/us/playlist/top-100-fiji/pl.1e2c1286034c49b78139d2b4ff499a94',
    },
    {
      name: 'finland',
      nameKorean: '핀란드',
      icon: '🇫🇮',
      url: 'https://music.apple.com/us/playlist/top-100-finland/pl.acea41a017664a8ebcd5aa1622aecc88',
    },
    {
      name: 'france',
      nameKorean: '프랑스',
      icon: '🇫🇷',
      url: 'https://music.apple.com/us/playlist/top-100-france/pl.6e8cfd81d51042648fa36c9df5236b8d',
    },
    {
      name: 'gambia',
      nameKorean: '감비아',
      icon: '🇬🇲',
      url: 'https://music.apple.com/us/playlist/top-100-gambia/pl.62e12ecd522d47858321846adcaac43d',
    },
    {
      name: 'germany',
      nameKorean: '독일',
      icon: '🇩🇪',
      url: 'https://music.apple.com/us/playlist/top-100-germany/pl.c10a2c113db14685a0b09fa5834d8e8b',
    },
    {
      name: 'ghana',
      nameKorean: '가나',
      icon: '🇬🇭',
      url: 'https://music.apple.com/us/playlist/top-100-ghana/pl.78f1974e882d4952b26ebfb8e017c933',
    },
    {
      name: 'greece',
      nameKorean: '그리스',
      icon: '🇬🇷',
      url: 'https://music.apple.com/us/playlist/top-100-greece/pl.0f15f3a8ba014979b9fdd7a0ef906dca',
    },
    {
      name: 'grenada',
      nameKorean: '그레나다',
      icon: '🇬🇩',
      url: 'https://music.apple.com/us/playlist/top-100-grenada/pl.b14c0257c1744d2686f88d05ab1efb4c',
    },
    {
      name: 'guatemala',
      nameKorean: '과테말라',
      icon: '🇬🇹',
      url: 'https://music.apple.com/us/playlist/top-100-guatemala/pl.7235b4236ee241f083f8026d372cc2d8',
    },
    {
      name: 'guinea-bissau',
      nameKorean: '기니비사우',
      icon: '🇬🇼',
      url: 'https://music.apple.com/us/playlist/top-100-guinea-bissau/pl.ac455234996b468b9f58e573752ab05c',
    },
    {
      name: 'honduras',
      nameKorean: '온두라스',
      icon: '🇭🇳',
      url: 'https://music.apple.com/us/playlist/top-100-honduras/pl.ec6d493f976349dfb0cba8f6c2f7e937',
    },
    {
      name: 'hong-kong',
      nameKorean: '홍콩',
      icon: '🇭🇰',
      url: 'https://music.apple.com/us/playlist/top-100-hong-kong/pl.7f35cffa10b54b91aab128ccc547f6ef',
    },
    {
      name: 'hungary',
      nameKorean: '헝가리',
      icon: '🇭🇺',
      url: 'https://music.apple.com/us/playlist/top-100-hungary/pl.cee165c3a51e466481bde5de75d6dee3',
    },
    {
      name: 'india',
      nameKorean: '인도',
      icon: '🇮🇳',
      url: 'https://music.apple.com/us/playlist/top-100-india/pl.c0e98d2423e54c39b3df955c24df3cc5',
    },
    {
      name: 'indonesia',
      nameKorean: '인도네시아',
      icon: '🇮🇩',
      url: 'https://music.apple.com/us/playlist/top-100-indonesia/pl.2b7e089dc9ef4dd7a18429df9c6e26a3',
    },
    {
      name: 'israel',
      nameKorean: '이스라엘',
      icon: '🇮🇱',
      url: 'https://music.apple.com/us/playlist/top-100-israel/pl.0c9765e5330048af96c2336fa7bc3525',
    },
    {
      name: 'italy',
      nameKorean: '이탈리아',
      icon: '🇮🇹',
      url: 'https://music.apple.com/us/playlist/top-100-italy/pl.737e067787df485a8062e2c4927d94db',
    },
    {
      name: 'japan',
      nameKorean: '일본',
      icon: '🇯🇵',
      url: 'https://music.apple.com/us/playlist/top-100-japan/pl.043a2c9876114d95a4659988497567be',
    },
    {
      name: 'jordan',
      nameKorean: '요르단',
      icon: '🇯🇴',
      url: 'https://music.apple.com/us/playlist/top-100-jordan/pl.5adf310412994d9483918fcd8e091fc5',
    },
    {
      name: 'kazakhstan',
      nameKorean: '카자흐스탄',
      icon: '🇰🇿',
      url: 'https://music.apple.com/us/playlist/top-100-kazakhstan/pl.27d3c4d63b0e41f29f79c98bb5a090e1',
    },
    {
      name: 'kenya',
      nameKorean: '케냐',
      icon: '🇰🇪',
      url: 'https://music.apple.com/us/playlist/top-100-kenya/pl.0b36ea82865d4adeb9d1d62207aab172',
    },
    {
      name: 'kyrgyzstan',
      nameKorean: '키르기스스탄',
      icon: '🇰🇬',
      url: 'https://music.apple.com/us/playlist/top-100-kyrgyzstan/pl.5318aa72adb84bcfac803ecaf6156325',
    },
    {
      name: 'laos',
      nameKorean: '라오스',
      icon: '🇱🇦',
      url: 'https://music.apple.com/us/playlist/top-100-laos/pl.42b3fe9c75a947ab84a80019e7bcd704',
    },
    {
      name: 'latvia',
      nameKorean: '라트비아',
      icon: '🇱🇻',
      url: 'https://music.apple.com/us/playlist/top-100-latvia/pl.5ac047a9ada144aebb9b2f16f5bc8c1d',
    },
    {
      name: 'lebanon',
      nameKorean: '레바논',
      icon: '🇱🇧',
      url: 'https://music.apple.com/us/playlist/top-100-lebanon/pl.838a4daba8924c42969ca7162fdc74da',
    },
    {
      name: 'lithuania',
      nameKorean: '리투아니아',
      icon: '🇱🇹',
      url: 'https://music.apple.com/us/playlist/top-100-lithuania/pl.e96de57d836e42dca30f7da24c64bbea',
    },
    {
      name: 'luxembourg',
      nameKorean: '룩셈부르크',
      icon: '🇱🇺',
      url: 'https://music.apple.com/us/playlist/top-100-luxembourg/pl.2f85377267d74a13be02a53882a5b488',
    },
    {
      name: 'malaysia',
      nameKorean: '말레이시아',
      icon: '🇲🇾',
      url: 'https://music.apple.com/us/playlist/top-100-malaysia/pl.a165defeeccb4b17a59bb5c85637b9b7',
    },
    {
      name: 'malta',
      nameKorean: '몰타',
      icon: '🇲🇹',
      url: 'https://music.apple.com/us/playlist/top-100-malta/pl.06ab782ba2324ae49317d6bde84eef56',
    },
    {
      name: 'mauritius',
      nameKorean: '모리셔스',
      icon: '🇲🇺',
      url: 'https://music.apple.com/us/playlist/top-100-mauritius/pl.5e6efed969354b378770c2ea6f2fed6b',
    },
    {
      name: 'mexico',
      nameKorean: '멕시코',
      icon: '🇲🇽',
      url: 'https://music.apple.com/us/playlist/top-100-mexico/pl.df3f10ca27b1479087de2cd3f9f6716b',
    },
    {
      name: 'mongolia',
      nameKorean: '몽골',
      icon: '🇲🇳',
      url: 'https://music.apple.com/us/playlist/top-100-mongolia/pl.71c450d15a9e4440ac5d24c174958225',
    },
    {
      name: 'nepal',
      nameKorean: '네팔',
      icon: '🇳🇵',
      url: 'https://music.apple.com/us/playlist/top-100-nepal/pl.9032e70a644e442688f120a829c636cd',
    },
    {
      name: 'netherlands',
      nameKorean: '네덜란드',
      icon: '🇳🇱',
      url: 'https://music.apple.com/us/playlist/top-100-netherlands/pl.26fb1998d54a4b3192be548529a97f8e',
    },
    {
      name: 'new-zealand',
      nameKorean: '뉴질랜드',
      icon: '🇳🇿',
      url: 'https://music.apple.com/us/playlist/top-100-new-zealand/pl.d8742df90f43402ba5e708eefd6d949a',
    },
    {
      name: 'nicaragua',
      nameKorean: '니카라과',
      icon: '🇳🇮',
      url: 'https://music.apple.com/us/playlist/top-100-nicaragua/pl.2249e0cc6edb46f4ae64de2c937a4f41',
    },
    {
      name: 'niger',
      nameKorean: '니제르',
      icon: '🇳🇪',
      url: 'https://music.apple.com/us/playlist/top-100-niger/pl.cd4a09b0acde49cda246819d9421b26b',
    },
    {
      name: 'nigeria',
      nameKorean: '나이지리아',
      icon: '🇳🇬',
      url: 'https://music.apple.com/us/playlist/top-100-nigeria/pl.2fc68f6d68004ae993dadfe99de83877',
    },
    {
      name: 'norway',
      nameKorean: '노르웨이',
      icon: '🇳🇴',
      url: 'https://music.apple.com/us/playlist/top-100-norway/pl.05a67957c3974729aac67c01247e55b6',
    },
    {
      name: 'oman',
      nameKorean: '오만',
      icon: '🇴🇲',
      url: 'https://music.apple.com/us/playlist/top-100-oman/pl.d4ca5698caf04a9f873861c3659aeeca',
    },
    {
      name: 'panama',
      nameKorean: '파나마',
      icon: '🇵🇦',
      url: 'https://music.apple.com/us/playlist/top-100-panama/pl.9d5ee7c72f804dbab97163616c7a8399',
    },
    {
      name: 'papua-new-guinea',
      nameKorean: '파푸아뉴기니',
      icon: '🇵🇬',
      url: 'https://music.apple.com/us/playlist/top-100-papua-new-guinea/pl.30fbe54afbf846edabdbe00e90095d04',
    },
    {
      name: 'paraguay',
      nameKorean: '파라과이',
      icon: '🇵🇾',
      url: 'https://music.apple.com/us/playlist/top-100-paraguay/pl.0843e61953c1430287162e5a36dff52b',
    },
    {
      name: 'peru',
      nameKorean: '페루',
      icon: '🇵🇪',
      url: 'https://music.apple.com/us/playlist/top-100-peru/pl.569a0034bcc64db68bb13afa8171a687',
    },
    {
      name: 'philippines',
      nameKorean: '필리핀',
      icon: '🇵🇭',
      url: 'https://music.apple.com/us/playlist/top-100-philippines/pl.b9eb00f9d195440e8b0bdf19b8db7f34',
    },
    {
      name: 'poland',
      nameKorean: '폴란드',
      icon: '🇵🇱',
      url: 'https://music.apple.com/us/playlist/top-100-poland/pl.8c91cbb0ef4e48308dbbba4238135eaf',
    },
    {
      name: 'portugal',
      nameKorean: '포르투갈',
      icon: '🇵🇹',
      url: 'https://music.apple.com/us/playlist/top-100-portugal/pl.5437c1490ac74e9e9505fc7d1f201655',
    },
    {
      name: 'moldova',
      nameKorean: '몰도바',
      icon: '🇲🇩',
      url: 'https://music.apple.com/us/playlist/top-100-moldova/pl.e4dcd4663130419bb03b80216dee9f57',
    },
    {
      name: 'romania',
      nameKorean: '루마니아',
      icon: '🇷🇴',
      url: 'https://music.apple.com/us/playlist/top-100-romania/pl.0c6bea611ad54c79b854299bc515a5a',
    },
    {
      name: 'saudi-arabia',
      nameKorean: '사우디아라비아',
      icon: '🇸🇦',
      url: 'https://music.apple.com/us/playlist/top-100-saudi-arabia/pl.a5365fa3b6ec4a34994339ca100801ae',
    },
    {
      name: 'singapore',
      nameKorean: '싱가포르',
      icon: '🇸🇬',
      url: 'https://music.apple.com/us/playlist/top-100-singapore/pl.4d763fa1cf15433b9994a14be6a46164',
    },
    {
      name: 'slovakia',
      nameKorean: '슬로바키아',
      icon: '🇸🇰',
      url: 'https://music.apple.com/us/playlist/top-100-slovakia/pl.2e50996a5bf44ab78cbb5c34b1992701',
    },
    {
      name: 'slovenia',
      nameKorean: '슬로베니아',
      icon: '🇸🇮',
      url: 'https://music.apple.com/us/playlist/top-100-slovenia/pl.e7374de32aec446c92136234d5bcae2f',
    },
    {
      name: 'south-africa',
      nameKorean: '남아프리카 공화국',
      icon: '🇿🇦',
      url: 'https://music.apple.com/us/playlist/top-100-south-africa/pl.447bd05172824b89bd745628f7f54c18',
    },
    {
      name: 'south-korea',
      nameKorean: '대한민국',
      icon: '🇰🇷',
      url: 'https://music.apple.com/us/playlist/top-100-south-korea/pl.d3d10c32fbc540b38e266367dc8cb00c',
    },
    {
      name: 'spain',
      nameKorean: '스페인',
      icon: '🇪🇸',
      url: 'https://music.apple.com/us/playlist/top-100-spain/pl.0d656d7feae64198bc5fb1b02786ed75',
    },
    {
      name: 'sri-lanka',
      nameKorean: '스리랑카',
      icon: '🇱🇰',
      url: 'https://music.apple.com/us/playlist/top-100-sri-lanka/pl.cd9b6c35086b43b193ecc3d32882a41e',
    },
    {
      name: 'st-kitts-and-nevis',
      nameKorean: '세인트키츠 네비스',
      icon: '🇰🇳',
      url: 'https://music.apple.com/us/playlist/top-100-st-kitts-and-nevis/pl.be7b2d63abaf4d25918ef41187f88be4',
    },
    {
      name: 'sweden',
      nameKorean: '스웨덴',
      icon: '🇸🇪',
      url: 'https://music.apple.com/us/playlist/top-100-sweden/pl.5876877c387b4ffb8860ac3ea2c244c3',
    },
    {
      name: 'switzerland',
      nameKorean: '스위스',
      icon: '🇨🇭',
      url: 'https://music.apple.com/us/playlist/top-100-switzerland/pl.bb1f5218a0f04de3877c4f9ccd63d260',
    },
    {
      name: 'taiwan',
      nameKorean: '대만',
      icon: '🇹🇼',
      url: 'https://music.apple.com/us/playlist/top-100-taiwan/pl.741ff34016704547853b953ec5181d83',
    },
    {
      name: 'tajikistan',
      nameKorean: '타지키스탄',
      icon: '🇹🇯',
      url: 'https://music.apple.com/us/playlist/top-100-tajikistan/pl.ea75568dc0524a479b818d551a7b3c35',
    },
    {
      name: 'thailand',
      nameKorean: '태국',
      icon: '🇹🇭',
      url: 'https://music.apple.com/us/playlist/top-100-thailand/pl.c509137d97214632a087129ece060a3d',
    },
    {
      name: 'trinidad-and-tobago',
      nameKorean: '트리니다드 토바고',
      icon: '🇹🇹',
      url: 'https://music.apple.com/us/playlist/top-100-trinidad-and-tobago/pl.f1495be1a9774341ab8a1eceb7011579',
    },
    {
      name: 'turkmenistan',
      nameKorean: '투르크메니스탄',
      icon: '🇹🇲',
      url: 'https://music.apple.com/us/playlist/top-100-turkmenistan/pl.f783d8aec4df401583434a2454adbc3d',
    },
    {
      name: 'uganda',
      nameKorean: '우간다',
      icon: '🇺🇬',
      url: 'https://music.apple.com/us/playlist/top-100-uganda/pl.b9e553253ed24c2a829c9c08209e5f67',
    },
    {
      name: 'uk',
      nameKorean: '영국',
      icon: '🇬🇧',
      url: 'https://music.apple.com/us/playlist/top-100-uk/pl.c2273b7e89b44121b3093f67228918e7',
    },
    {
      name: 'usa',
      nameKorean: '미국',
      icon: '🇺🇸',
      url: 'https://music.apple.com/us/playlist/top-100-usa/pl.606afcbb70264d2eb2b51d8dbcfa6a12',
    },
    {
      name: 'ukraine',
      nameKorean: '우크라이나',
      icon: '🇺🇦',
      url: 'https://music.apple.com/us/playlist/top-100-ukraine/pl.815f78effb3844909a8259d759ecbddb',
    },
    {
      name: 'united-arab-emirates',
      nameKorean: '아랍에미리트',
      icon: '🇦🇪',
      url: 'https://music.apple.com/us/playlist/top-100-united-arab-emirates/pl.7b5e51f09aee4733958e23ea97dda459',
    },
    {
      name: 'uzbekistan',
      nameKorean: '우즈베키스탄',
      icon: '🇺🇿',
      url: 'https://music.apple.com/us/playlist/top-100-uzbekistan/pl.90ad69a600ed4d10b00d158eea68cad7',
    },
    {
      name: 'venezuela',
      nameKorean: '베네수엘라',
      icon: '🇻🇪',
      url: 'https://music.apple.com/us/playlist/top-100-venezuela/pl.617da0e0bbb74461b607cad435b1e941',
    },
    {
      name: 'vietnam',
      nameKorean: '베트남',
      icon: '🇻🇳',
      url: 'https://music.apple.com/us/playlist/top-100-vietnam/pl.550110ec6feb4ae0aff364bcde6d1372',
    },
    {
      name: 'zimbabwe',
      nameKorean: '짐바브웨',
      icon: '🇿🇼',
      url: 'https://music.apple.com/us/playlist/top-100-zimbabwe/pl.ad37160bb16c4c70a1d83d3670e96c1a',
    },
  ],
  spotifyCountry: [
    {
      name: 'global',
      nameKorean: '글로벌',
      icon: '🌏',
      url: 'https://charts.spotify.com/charts/view/regional-global-daily/latest',
    },
    {
      name: 'argentina',
      nameKorean: '아르헨티나',
      icon: '🇦🇷',
      url: 'https://charts.spotify.com/charts/view/regional-ar-daily/latest',
    },
    {
      name: 'australia',
      nameKorean: '호주',
      icon: '🇦🇺',
      url: 'https://charts.spotify.com/charts/view/regional-au-daily/latest',
    },
    {
      name: 'austria',
      nameKorean: '오스트리아',
      icon: '🇦🇹',
      url: 'https://charts.spotify.com/charts/view/regional-at-daily/latest',
    },
    {
      name: 'belarus',
      nameKorean: '벨라루스',
      icon: '🇧🇾',
      url: 'https://charts.spotify.com/charts/view/regional-by-daily/latest',
    },
    {
      name: 'belgium',
      nameKorean: '벨기에',
      icon: '🇧🇪',
      url: 'https://charts.spotify.com/charts/view/regional-be-daily/latest',
    },
    {
      name: 'bolivia',
      nameKorean: '볼리비아',
      icon: '🇧🇴',
      url: 'https://charts.spotify.com/charts/view/regional-bo-daily/latest',
    },
    {
      name: 'brazil',
      nameKorean: '브라질',
      icon: '🇧🇷',
      url: 'https://charts.spotify.com/charts/view/regional-br-daily/latest',
    },
    {
      name: 'bulgaria',
      nameKorean: '불가리아',
      icon: '🇧🇬',
      url: 'https://charts.spotify.com/charts/view/regional-bg-daily/latest',
    },
    {
      name: 'canada',
      nameKorean: '캐나다',
      icon: '🇨🇦',
      url: 'https://charts.spotify.com/charts/view/regional-ca-daily/latest',
    },
    {
      name: 'chile',
      nameKorean: '칠레',
      icon: '🇨🇱',
      url: 'https://charts.spotify.com/charts/view/regional-cl-daily/latest',
    },
    {
      name: 'colombia',
      nameKorean: '콜롬비아',
      icon: '🇨🇴',
      url: 'https://charts.spotify.com/charts/view/regional-co-daily/latest',
    },
    {
      name: 'costa-rica',
      nameKorean: '코스타리카',
      icon: '🇨🇷',
      url: 'https://charts.spotify.com/charts/view/regional-cr-daily/latest',
    },
    {
      name: 'czech-republic',
      nameKorean: '체코',
      icon: '🇨🇿',
      url: 'https://charts.spotify.com/charts/view/regional-cz-daily/latest',
    },
    {
      name: 'denmark',
      nameKorean: '덴마크',
      icon: '🇩🇰',
      url: 'https://charts.spotify.com/charts/view/regional-dk-daily/latest',
    },
    {
      name: 'dominican-republic',
      nameKorean: '도미니카공화국',
      icon: '🇩🇴',
      url: '',
    },
    {
      name: 'ecuador',
      nameKorean: '에콰도르',
      icon: '🇪🇨',
      url: 'https://charts.spotify.com/charts/view/regional-ec-daily/latest',
    },
    {
      name: 'egypt',
      nameKorean: '이집트',
      icon: '🇪🇬',
      url: 'https://charts.spotify.com/charts/view/regional-eg-daily/latest',
    },
    {
      name: 'el-salvador',
      nameKorean: '엘살바도르',
      icon: '🇸🇻',
      url: 'https://charts.spotify.com/charts/view/regional-sv-daily/latest',
    },
    {
      name: 'estonia',
      nameKorean: '에스토니아',
      icon: '🇪🇪',
      url: 'https://charts.spotify.com/charts/view/regional-ee-daily/latest',
    },
    {
      name: 'finland',
      nameKorean: '핀란드',
      icon: '🇫🇮',
      url: 'https://charts.spotify.com/charts/view/regional-fi-daily/latest',
    },
    {
      name: 'france',
      nameKorean: '프랑스',
      icon: '🇫🇷',
      url: 'https://charts.spotify.com/charts/view/regional-fr-daily/latest',
    },
    {
      name: 'germany',
      nameKorean: '독일',
      icon: '🇩🇪',
      url: 'https://charts.spotify.com/charts/view/regional-de-daily/latest',
    },
    {
      name: 'greece',
      nameKorean: '그리스',
      icon: '🇬🇷',
      url: 'https://charts.spotify.com/charts/view/regional-gr-daily/latest',
    },
    {
      name: 'guatemala',
      nameKorean: '과테말라',
      icon: '🇬🇹',
      url: 'https://charts.spotify.com/charts/view/regional-gt-daily/latest',
    },
    {
      name: 'honduras',
      nameKorean: '온두라스',
      icon: '🇭🇳',
      url: 'https://charts.spotify.com/charts/view/regional-hn-daily/latest',
    },
    {
      name: 'hong-kong',
      nameKorean: '홍콩',
      icon: '🇭🇰',
      url: 'https://charts.spotify.com/charts/view/regional-hk-daily/latest',
    },
    {
      name: 'hungary',
      nameKorean: '헝가리',
      icon: '🇭🇺',
      url: 'https://charts.spotify.com/charts/view/regional-hu-daily/latest',
    },
    {
      name: 'iceland',
      nameKorean: '아이슬란드',
      icon: '🇮🇸',
      url: 'https://charts.spotify.com/charts/view/regional-is-daily/latest',
    },
    {
      name: 'india',
      nameKorean: '인도',
      icon: '🇮🇳',
      url: 'https://charts.spotify.com/charts/view/regional-in-daily/latest',
    },
    {
      name: 'indonesia',
      nameKorean: '인도네시아',
      icon: '🇮🇩',
      url: 'https://charts.spotify.com/charts/view/regional-id-daily/latest',
    },
    {
      name: 'ireland',
      nameKorean: '아일랜드',
      icon: '🇮🇪',
      url: 'https://charts.spotify.com/charts/view/regional-ie-daily/latest',
    },
    {
      name: 'israel',
      nameKorean: '이스라엘',
      icon: '🇮🇱',
      url: 'https://charts.spotify.com/charts/view/regional-il-daily/latest',
    },
    {
      name: 'italy',
      nameKorean: '이탈리아',
      icon: '🇮🇹',
      url: 'https://charts.spotify.com/charts/view/regional-it-daily/latest',
    },
    {
      name: 'japan',
      nameKorean: '일본',
      icon: '🇯🇵',
      url: 'https://charts.spotify.com/charts/view/regional-jp-daily/latest',
    },
    {
      name: 'kazakhstan',
      nameKorean: '카자흐스탄',
      icon: '🇰🇿',
      url: 'https://charts.spotify.com/charts/view/regional-kz-daily/latest',
    },
    {
      name: 'latvia',
      nameKorean: '라트비아',
      icon: '🇱🇻',
      url: 'https://charts.spotify.com/charts/view/regional-lv-daily/latest',
    },
    {
      name: 'lithuania',
      nameKorean: '리투아니아',
      icon: '🇱🇹',
      url: 'https://charts.spotify.com/charts/view/regional-lt-daily/latest',
    },
    {
      name: 'luxembourg',
      nameKorean: '룩셈부르크',
      icon: '🇱🇺',
      url: 'https://charts.spotify.com/charts/view/regional-lu-daily/latest',
    },
    {
      name: 'malaysia',
      nameKorean: '말레이시아',
      icon: '🇲🇾',
      url: 'https://charts.spotify.com/charts/view/regional-my-daily/latest',
    },
    {
      name: 'mexico',
      nameKorean: '멕시코',
      icon: '🇲🇽',
      url: 'https://charts.spotify.com/charts/view/regional-mx-daily/latest',
    },
    {
      name: 'morocco',
      nameKorean: '모로코',
      icon: '🇲🇦',
      url: 'https://charts.spotify.com/charts/view/regional-ma-daily/latest',
    },
    {
      name: 'netherlands',
      nameKorean: '네덜란드',
      icon: '🇳🇱',
      url: 'https://charts.spotify.com/charts/view/regional-nl-daily/latest',
    },
    {
      name: 'new-zealand',
      nameKorean: '뉴질랜드',
      icon: '🇳🇿',
      url: 'https://charts.spotify.com/charts/view/regional-nz-daily/latest',
    },
    {
      name: 'nicaragua',
      nameKorean: '니카라과',
      icon: '🇳🇮',
      url: 'https://charts.spotify.com/charts/view/regional-ni-daily/latest',
    },
    {
      name: 'norway',
      nameKorean: '노르웨이',
      icon: '🇳🇴',
      url: 'https://charts.spotify.com/charts/view/regional-no-daily/latest',
    },
    {
      name: 'pakistan',
      nameKorean: '파키스탄',
      icon: '🇵🇰',
      url: 'https://charts.spotify.com/charts/view/regional-pk-daily/latest',
    },
    {
      name: 'panama',
      nameKorean: '파나마',
      icon: '🇵🇦',
      url: 'https://charts.spotify.com/charts/view/regional-pa-daily/latest',
    },
    {
      name: 'paraguay',
      nameKorean: '파라과이',
      icon: '🇵🇾',
      url: 'https://charts.spotify.com/charts/view/regional-py-daily/latest',
    },
    {
      name: 'peru',
      nameKorean: '페루',
      icon: '🇵🇪',
      url: 'https://charts.spotify.com/charts/view/regional-pe-daily/latest',
    },
    {
      name: 'philippines',
      nameKorean: '필리핀',
      icon: '🇵🇭',
      url: 'https://charts.spotify.com/charts/view/regional-ph-daily/latest',
    },
    {
      name: 'poland',
      nameKorean: '폴란드',
      icon: '🇵🇱',
      url: 'https://charts.spotify.com/charts/view/regional-pl-daily/latest',
    },
    {
      name: 'portugal',
      nameKorean: '포르투갈',
      icon: '🇵🇹',
      url: 'https://charts.spotify.com/charts/view/regional-pt-daily/latest',
    },
    {
      name: 'romania',
      nameKorean: '루마니아',
      icon: '🇷🇴',
      url: 'https://charts.spotify.com/charts/view/regional-ro-daily/latest',
    },
    {
      name: 'saudi-arabia',
      nameKorean: '사우디아라비아',
      icon: '🇸🇦',
      url: 'https://charts.spotify.com/charts/view/regional-sa-daily/latest',
    },
    {
      name: 'singapore',
      nameKorean: '싱가포르',
      icon: '🇸🇬',
      url: 'https://charts.spotify.com/charts/view/regional-sg-daily/latest',
    },
    {
      name: 'slovakia',
      nameKorean: '슬로바키아',
      icon: '🇸🇰',
      url: 'https://charts.spotify.com/charts/view/regional-sk-daily/latest',
    },
    {
      name: 'south-africa',
      nameKorean: '남아프리카',
      icon: '🇿🇦',
      url: 'https://charts.spotify.com/charts/view/regional-za-daily/latest',
    },
    {
      name: 'south-korea',
      nameKorean: '대한민국',
      icon: '🇰🇷',
      url: 'https://charts.spotify.com/charts/view/regional-kr-daily/latest',
    },
    {
      name: 'spain',
      nameKorean: '스페인',
      icon: '🇪🇸',
      url: 'https://charts.spotify.com/charts/view/regional-es-daily/latest',
    },
    {
      name: 'sweden',
      nameKorean: '스웨덴',
      icon: '🇸🇪',
      url: 'https://charts.spotify.com/charts/view/regional-se-daily/latest',
    },
    {
      name: 'switzerland',
      nameKorean: '스위스',
      icon: '🇨🇭',
      url: 'https://charts.spotify.com/charts/view/regional-ch-daily/latest',
    },
    {
      name: 'taiwan',
      nameKorean: '대만',
      icon: '🇹🇼',
      url: 'https://charts.spotify.com/charts/view/regional-tw-daily/latest',
    },
    {
      name: 'thailand',
      nameKorean: '태국',
      icon: '🇹🇭',
      url: 'https://charts.spotify.com/charts/view/regional-th-daily/latest',
    },
    {
      name: 'turkey',
      nameKorean: '터키',
      icon: '🇹🇷',
      url: 'https://charts.spotify.com/charts/view/regional-tr-daily/latest',
    },
    {
      name: 'united-arab-emirates',
      nameKorean: '아랍에미리트',
      icon: '🇦🇪',
      url: 'https://charts.spotify.com/charts/view/regional-us-daily/latest',
    },
    {
      name: 'ukraine',
      nameKorean: '우크라이나',
      icon: '🇺🇦',
      url: 'https://charts.spotify.com/charts/view/regional-ua-daily/latest',
    },
    {
      name: 'uk',
      nameKorean: '영국',
      icon: '🇬🇧',
      url: 'https://charts.spotify.com/charts/view/regional-gb-daily/latest',
    },
    {
      name: 'uruguay',
      nameKorean: '우루과이',
      icon: '🇺🇾',
      url: 'https://charts.spotify.com/charts/view/regional-uy-daily/latest',
    },
    {
      name: 'usa',
      nameKorean: '미국',
      icon: '🇺🇸',
      url: 'https://charts.spotify.com/charts/view/regional-us-daily/latest',
    },
    {
      name: 'venezuela',
      nameKorean: '베네수엘라',
      icon: '🇻🇪',
      url: 'https://charts.spotify.com/charts/view/regional-ve-daily/latest',
    },
    {
      name: 'vietnam',
      nameKorean: '베트남',
      icon: '🇻🇳',
      url: 'https://charts.spotify.com/charts/view/regional-vn-daily/latest',
    },
  ],
}

export default data
